# Generated by Django 3.0.8 on 2020-08-05 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room_nm', models.CharField(max_length=200, null=True)),
                ('reg_dtti', models.DateTimeField(auto_now_add=True)),
                ('ptr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqr_info', to=settings.AUTH_USER_MODEL)),
                ('reqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptr_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_id', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('reg_dtti', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Chat_room')),
            ],
        ),
    ]
