# Generated by Django 3.0.8 on 2020-07-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_extend',
            old_name='reqr_join_yn',
            new_name='ptr_join_yn',
        ),
    ]
