# Generated by Django 3.0.8 on 2020-07-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200727_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extend',
            name='del_res',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_extend',
            name='staff_cnt',
            field=models.IntegerField(null=True),
        ),
    ]
