# Generated by Django 3.0.8 on 2020-07-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200727_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_extend',
            name='biz_nm',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
