# Generated by Django 3.0.8 on 2020-07-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200727_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extend',
            name='career',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_extend',
            name='del_yn',
            field=models.CharField(default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user_extend',
            name='user_type',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
