# Generated by Django 3.0.8 on 2020-08-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200801_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extend',
            name='career',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='user_extend',
            name='staff_cnt',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
