# Generated by Django 3.0.8 on 2020-08-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200801_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_extend',
            name='actv_area',
        ),
        migrations.AddField(
            model_name='user_extend',
            name='area_sido',
            field=models.CharField(default='서울특별시', max_length=50),
        ),
        migrations.AddField(
            model_name='user_extend',
            name='area_sigungu',
            field=models.CharField(default='강남구', max_length=50),
        ),
    ]
