# Generated by Django 3.0.8 on 2020-08-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200807_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extend',
            name='prof_img',
            field=models.ImageField(blank=True, default='icon.png', null=True, upload_to='profile'),
        ),
    ]
