# Generated by Django 3.0.8 on 2020-08-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200807_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extend',
            name='prof_img',
            field=models.ImageField(default='icon.png', upload_to='profile'),
        ),
    ]
