# Generated by Django 3.0.8 on 2020-07-26 20:50

from django.conf import settings
from django.db import migrations, models
import requests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cont', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='requests')),
                ('req_area', models.CharField(max_length=100)),
                ('svc_cd', models.CharField(max_length=6)),
                ('work_spc_kind', models.CharField(max_length=20)),
                ('elev_psb_yn', models.CharField(max_length=1)),
                ('size', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('req_exp_stt_dt', models.DateField()),
                ('req_exp_end_dt', models.DateField()),
                ('work_stt_dt', models.DateField()),
                ('work_end_dt', models.DateField()),
                ('del_yn', models.CharField(default='N', max_length=1)),
                ('reg_dtti', models.DateTimeField(auto_now_add=True)),
                ('mod_dtti', models.DateTimeField(auto_now=True)),
                ('reqr_username', models.ForeignKey(on_delete=models.SET(requests.models.set_none), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
