# Generated by Django 3.0.8 on 2020-08-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20200801_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='req_exp_end_dt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_exp_stt_dt',
            field=models.DateField(null=True),
        ),
    ]
