# Generated by Django 3.0.8 on 2020-08-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20200807_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_img',
            name='img',
            field=models.ImageField(upload_to='request'),
        ),
    ]
