# Generated by Django 3.0.8 on 2020-07-26 20:50

from django.conf import settings
from django.db import migrations, models
import estimates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('cont', models.TextField()),
                ('del_yn', models.CharField(default='N', max_length=1)),
                ('reg_dtti', models.DateTimeField(auto_now_add=True)),
                ('mod_dtti', models.DateTimeField(auto_now=True)),
                ('ptr_username', models.ForeignKey(on_delete=models.SET(estimates.models.set_none), to=settings.AUTH_USER_MODEL)),
                ('req_id', models.ForeignKey(on_delete=models.SET(estimates.models.set_none), to='requests.Request')),
            ],
        ),
    ]
