# Generated by Django 3.0.8 on 2020-07-29 10:17

from django.db import migrations, models
import estimates.models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='cont',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='req_id',
            field=models.ForeignKey(on_delete=models.SET(estimates.models.set_none), related_name='related_request', to='requests.Request'),
        ),
    ]
