# Generated by Django 3.0.8 on 2020-07-29 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('svc_cd', models.CharField(max_length=6)),
                ('work_spc_kind', models.CharField(max_length=20)),
                ('work_ym', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=100)),
                ('cont', models.TextField()),
                ('reg_dtti', models.DateTimeField(auto_now_add=True)),
                ('mod_dtti', models.DateTimeField(auto_now=True)),
                ('ptr_username', models.ForeignKey(on_delete=models.SET(portfolio.models.set_none), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio')),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
            ],
        ),
    ]
