# Generated by Django 3.0.8 on 2020-08-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_image_main_yn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Portfolio_img',
        ),
        migrations.RenameField(
            model_name='portfolio_img',
            old_name='image',
            new_name='img',
        ),
    ]
