# Generated by Django 3.0.8 on 2020-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200801_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='svc_cd',
            field=models.CharField(max_length=30),
        ),
    ]
